
version: '2'
services:
  redis:
    image: redis
    restart: always
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /srv/pgr/db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  pgr:
    image: lcasuol/pgr_system:0.0.18
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_DATE
        - SOURCE_COMMIT
        - VERSION      
    restart: always
    #build: . 
    command: "bash -c 'if [ -r /srv/config/.htaccess ]; then ln -fsv /srv/config/.htaccess /var/www/html/pgr/public/.htaccess; fi && ln -fsv /srv/config/.env /var/www/html/pgr/.env && /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf'"
    links:
      - db
      - redis
      - smtp
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/pgr/storage:/var/www/html/pgr/storage
      - /srv/pgr/config:/srv/config
  
  smtp:
    image: djfarrelly/maildev
    command: "bin/maildev --web 80 --smtp 25 --outgoing-host mailslot.lincoln.ac.uk --outgoing-port 25 --base-pathname /maildev --auto-relay marc@hanheide.net"
    volumes:
      - /srv/maildev/storage:/tmp/maildev
    ports:
      - "8090:80"
      - "1025:25"

  mysqldump:
    image: schnitzler/mysqldump
    restart: always
    volumes:
      - ./db-backup.sh:/etc/periodic/daily/backup
      - /srv/pgr/storage:/backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: pgr_saml

