
version: '2'
services:
  redis:
    image: redis
  db:
    image: mysql
    volumes:
      - /srv/pgr/db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  pgr:
    image: lcasuol/pgr_system:lcas
    #build: . 
    command: "bash -c 'ln -fs /srv/config/.env /var/www/html/pgr/.env && /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf'"
    links:
      - db
      - redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/pgr/storage:/var/www/html/pgr/storage
      - /srv/pgr/config:/srv/config

  mysqldump:
    image: schnitzler/mysqldump
    restart: always
    volumes:
      - ./db-backup.sh:/etc/periodic/daily/backup
      - /srv/pgr/storage:/backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: pgr_saml

